### ISSUE TITLE
图片链接失效

### ISSUE THREAD

**Issue by Endlinc** [yinwenqin/kubeSourceCodeNote#2]
网站的md文档中链接的图片失效，如下图：
![image](https://user-images.githubusercontent.com/34116526/165202787-86a438c1-4e68-4ef3-824d-1fc1865b957a.png)

**Comment by yinwenqin** [comment]
上传的md文档中的原图片链接会被替换成github cdn链接，如果加载不出来，应该是墙内网络的问题
<img width="1573" alt="image" src="https://user-images.githubusercontent.com/31464022/165203420-8c10fbb2-d18e-40a8-9337-6bab4d7be3f1.png">
